# Generated by Django 5.0.2 on 2024-08-29 12:04

import Core.models
import django.db.models.deletion
import shortuuid.django_fields
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh', length=10, max_length=20, prefix='gen', unique=True)),
                ('title', models.CharField(default='', max_length=100)),
                ('order', models.IntegerField(default='1')),
            ],
            options={
                'verbose_name_plural': 'Generations',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', shortuuid.django_fields.ShortUUIDField(alphabet='0123456789', length=25, max_length=30, prefix='ord', unique=True)),
                ('order_number', models.CharField(default='ORDER_NUMBER-0', editable=False, max_length=200)),
                ('order_price', models.DecimalField(decimal_places=2, default='0', editable=False, max_digits=999)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('order_status', models.CharField(choices=[('packing', 'Packing'), ('packed', 'Packed'), ('label_made', 'Label Made'), ('shipped', 'Shipped')], default='packing', max_length=30)),
                ('tracking_number', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('customer_email', models.EmailField(blank=True, editable=False, max_length=254, null=True)),
                ('address', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh', length=10, max_length=20, prefix='cat', unique=True)),
                ('title', models.CharField(default='', max_length=100)),
                ('generation', models.ManyToManyField(to='Core.generation')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_one', models.CharField(max_length=100, null=True)),
                ('address_line_two', models.CharField(max_length=100, null=True)),
                ('address_city', models.CharField(max_length=100, null=True)),
                ('address_zip_code', models.CharField(max_length=100, null=True)),
                ('address_state', models.CharField(max_length=100, null=True)),
                ('address_country', models.CharField(max_length=100, null=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_bill_address', to='Core.order')),
            ],
            options={
                'verbose_name_plural': 'Billing Address',
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh', editable=False, length=10, max_length=20, prefix='prd')),
                ('title', models.CharField(default='Beyblade', editable=False, max_length=100)),
                ('image', models.ImageField(default='product.jpg', editable=False, upload_to=Core.models.user_directory_path)),
                ('price', models.DecimalField(decimal_places=2, default='99.99', editable=False, max_digits=999)),
                ('quantity', models.IntegerField(default='1', editable=False)),
                ('total_price', models.DecimalField(decimal_places=2, default='0.00', editable=False, max_digits=999)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='Core.order')),
            ],
            options={
                'verbose_name_plural': 'Order Items',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh', length=10, max_length=20, prefix='prd', unique=True)),
                ('title', models.CharField(default='Beyblade', max_length=100)),
                ('image', models.ImageField(default='product.jpg', upload_to=Core.models.user_directory_path)),
                ('description', tinymce.models.HTMLField(blank=True, default='This is the product', null=True)),
                ('price', models.DecimalField(decimal_places=2, default='99.99', max_digits=999)),
                ('old_price', models.DecimalField(decimal_places=2, default='199.99', max_digits=999)),
                ('quantity', models.IntegerField(default='1')),
                ('specifications', tinymce.models.HTMLField(blank=True, null=True)),
                ('product_status', models.CharField(choices=[('drafts', 'Drafts'), ('disabled', 'Disabled'), ('rejected', 'Rejected'), ('in_review', 'In Review'), ('published', 'Published'), ('sold_out', 'Sold Out')], default='in_review', max_length=10)),
                ('featured', models.BooleanField(default=False)),
                ('sku', shortuuid.django_fields.ShortUUIDField(alphabet='0123456789', length=4, max_length=10, prefix='sku', unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('generation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.generation')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(default='product.jpg', upload_to='products-images')),
                ('date', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_images', to='Core.product')),
            ],
            options={
                'verbose_name_plural': 'Product Images',
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], default=None)),
                ('date', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Product Reviews',
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_one', models.CharField(max_length=100, null=True)),
                ('address_line_two', models.CharField(max_length=100, null=True)),
                ('address_city', models.CharField(max_length=100, null=True)),
                ('address_zip_code', models.CharField(max_length=100, null=True)),
                ('address_state', models.CharField(max_length=100, null=True)),
                ('address_country', models.CharField(max_length=100, null=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_ship_address', to='Core.order')),
            ],
            options={
                'verbose_name_plural': 'Shipping Address',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh', length=10, max_length=20, prefix='ven', unique=True)),
                ('title', models.CharField(default='CatOnTheRoof', max_length=100)),
                ('image', models.ImageField(default='vendor.jpg', upload_to=Core.models.user_directory_path)),
                ('description', tinymce.models.HTMLField(blank=True, default='I am a Vendor', null=True)),
                ('address', models.CharField(default='123 Main Street', max_length=100)),
                ('contact', models.CharField(default='860-555-5050', max_length=100)),
                ('chat_resp_time', models.CharField(default='100', max_length=100)),
                ('shipping_on_time', models.CharField(default='100', max_length=100)),
                ('authentic_rating', models.CharField(default='100', max_length=100)),
                ('days_return', models.CharField(default='100', max_length=100)),
                ('warranty_period', models.CharField(default='100', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Vendors',
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Wishlists',
            },
        ),
    ]
