# Generated by Django 5.0.2 on 2024-09-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_customuser_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_permission',
            field=models.BooleanField(default=True),
        ),
    ]
