# Generated by Django 5.0.2 on 2024-08-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionSwitch',
            fields=[
                ('production_switch', models.CharField(choices=[('locked', 'Locked'), ('production', 'Production'), ('testing', 'Testing')], default='locked', max_length=15)),
                ('contsraint', models.IntegerField(default=1, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Production Switch',
                'managed': True,
            },
        ),
        migrations.AddConstraint(
            model_name='productionswitch',
            constraint=models.UniqueConstraint(condition=models.Q(('contsraint', 1)), fields=('contsraint',), name='only_one_production_switch'),
        ),
    ]
