# Generated by Django 5.0.2 on 2024-08-29 12:03

import shortuuid.django_fields
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us_id', shortuuid.django_fields.ShortUUIDField(alphabet='0123456789', length=6, max_length=15, prefix='about', unique=True)),
                ('about_us_text', tinymce.models.HTMLField()),
                ('used', models.BooleanField(default=False, verbose_name='Is Used')),
            ],
            options={
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_id', shortuuid.django_fields.ShortUUIDField(alphabet='0123456789', length=10, max_length=15, prefix='faq', unique=True)),
                ('faq_text', tinymce.models.HTMLField()),
                ('used', models.BooleanField(default=False, verbose_name='Is Used')),
            ],
            options={
                'verbose_name_plural': 'FAQ',
            },
        ),
        migrations.CreateModel(
            name='OurServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_services_id', shortuuid.django_fields.ShortUUIDField(alphabet='0123456789', length=10, max_length=15, prefix='service', unique=True)),
                ('our_services_text', tinymce.models.HTMLField()),
                ('used', models.BooleanField(default=False, verbose_name='Is Used')),
            ],
            options={
                'verbose_name_plural': 'Our Services',
            },
        ),
        migrations.CreateModel(
            name='PaymentOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_options_id', shortuuid.django_fields.ShortUUIDField(alphabet='0123456789', length=10, max_length=15, prefix='payment', unique=True)),
                ('payment_options_text', tinymce.models.HTMLField()),
                ('used', models.BooleanField(default=False, verbose_name='Is Used')),
            ],
            options={
                'verbose_name_plural': 'Payment Options',
            },
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacy_policy_id', shortuuid.django_fields.ShortUUIDField(alphabet='0123456789', length=10, max_length=15, prefix='privacy', unique=True)),
                ('privacy_policy_text', tinymce.models.HTMLField()),
                ('used', models.BooleanField(default=False, verbose_name='Is Used')),
            ],
            options={
                'verbose_name_plural': 'Privacy Policy',
            },
        ),
        migrations.CreateModel(
            name='ReturnPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_policy_id', shortuuid.django_fields.ShortUUIDField(alphabet='0123456789', length=10, max_length=15, prefix='return', unique=True)),
                ('return_policy_text', tinymce.models.HTMLField()),
                ('used', models.BooleanField(default=False, verbose_name='Is Used')),
            ],
            options={
                'verbose_name_plural': 'Return Policy',
            },
        ),
        migrations.CreateModel(
            name='ShippingPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_policy_id', shortuuid.django_fields.ShortUUIDField(alphabet='0123456789', length=10, max_length=15, prefix='shipping', unique=True)),
                ('shipping_policy_text', tinymce.models.HTMLField()),
                ('used', models.BooleanField(default=False, verbose_name='Is Used')),
            ],
            options={
                'verbose_name_plural': 'Shipping Policy',
            },
        ),
        migrations.CreateModel(
            name='TermsOfService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_of_service_id', shortuuid.django_fields.ShortUUIDField(alphabet='0123456789', length=10, max_length=15, prefix='terms', unique=True)),
                ('terms_of_service_text', tinymce.models.HTMLField()),
                ('used', models.BooleanField(default=False, verbose_name='Is Used')),
            ],
            options={
                'verbose_name_plural': 'Terms of Service',
            },
        ),
        migrations.AddConstraint(
            model_name='aboutus',
            constraint=models.UniqueConstraint(condition=models.Q(('used', True)), fields=('used',), name='one_text_per_about'),
        ),
        migrations.AddConstraint(
            model_name='faq',
            constraint=models.UniqueConstraint(condition=models.Q(('used', True)), fields=('used',), name='one_text_per_faq'),
        ),
        migrations.AddConstraint(
            model_name='ourservices',
            constraint=models.UniqueConstraint(condition=models.Q(('used', True)), fields=('used',), name='one_text_per_service'),
        ),
        migrations.AddConstraint(
            model_name='paymentoptions',
            constraint=models.UniqueConstraint(condition=models.Q(('used', True)), fields=('used',), name='one_text_per_payment_options'),
        ),
        migrations.AddConstraint(
            model_name='privacypolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('used', True)), fields=('used',), name='one_text_per_privacy_policy'),
        ),
        migrations.AddConstraint(
            model_name='returnpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('used', True)), fields=('used',), name='one_text_per_return_policy'),
        ),
        migrations.AddConstraint(
            model_name='shippingpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('used', True)), fields=('used',), name='one_text_per_shipping_policy'),
        ),
        migrations.AddConstraint(
            model_name='termsofservice',
            constraint=models.UniqueConstraint(condition=models.Q(('used', True)), fields=('used',), name='one_text_per_terms_of_service'),
        ),
    ]
