# Generated by Django 5.0.2 on 2024-09-08 16:22

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Policy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='about_us_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='0123456789', length=10, max_length=15, prefix='about', unique=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='faq_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='0123456789', length=10, max_length=13, prefix='faq', unique=True),
        ),
        migrations.AlterField(
            model_name='ourservices',
            name='our_services_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='0123456789', length=10, max_length=17, prefix='service', unique=True),
        ),
        migrations.AlterField(
            model_name='paymentoptions',
            name='payment_options_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='0123456789', length=10, max_length=17, prefix='payment', unique=True),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='privacy_policy_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='0123456789', length=10, max_length=17, prefix='privacy', unique=True),
        ),
        migrations.AlterField(
            model_name='returnpolicy',
            name='return_policy_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='0123456789', length=10, max_length=16, prefix='return', unique=True),
        ),
        migrations.AlterField(
            model_name='shippingpolicy',
            name='shipping_policy_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='0123456789', length=10, max_length=18, prefix='shipping', unique=True),
        ),
    ]
